import { PullRequestResponse, RepoContext } from './types';

export async function createPullRequest(
  context: RepoContext,
  sourceBranch: string,
  packageName: string,
  newVersion: string,
): Promise<PullRequestResponse> {
  const title = `Update ${packageName} to version ${newVersion}`;
  const description = `This PR updates ${packageName} to version ${newVersion}.\n\nAutomatically generated by package update script.`;

  return context.client.post<PullRequestResponse>(
    `/repositories/${context.workspace}/${context.repo}/pullrequests`,
    {
      title,
      description,
      source: {
        branch: {
          name: sourceBranch,
        },
      },
      destination: {
        branch: {
          name: context.branch,
        },
      },
    },
  );
}
